name = "cloudflare-worker-kv"
main = "index.js"
account_id = "dac488296f82bed8d5733909d76ec455"
workers_dev = true
compatibility_date = "2024-04-20"

kv_namespaces = [
  { binding = "ai-chat-config", id = "25324acc63c346e490ca65882bdbc9bc" }
]

[env.production]
kv_namespaces = [
  { binding = "ai-chat-config", id = "25324acc63c346e490ca65882bdbc9bc" }
]

[observability.logs]
enabled = true
